/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Provider {
  Vanilla = 'Vanilla',
  Paper = 'Paper',
  Fabric = 'Fabric',
  Forge = 'Forge'
}
export interface MinecraftServer {
  id: string
  name: string
  instancePath: string
  version: string
  status: string
  provider: Provider
  port: number
  ram: number
}
export interface CloudflaredRespone {
  url: string
  status: string
  connections: Array<string>
}
export interface ContainerConfig {
  serverId: string
  jarPath: string
  port: number
  ramMb: number
  enableRcon: boolean
  onlineMode: boolean
}
export declare function startCloudflared(port: number, dataDir: string): Promise<CloudflaredRespone>
export declare function stopCloudflared(): string
export declare function clientConnect(url: string, dataDir: string): Promise<string>
export declare function startNginx(dataDir: string): string
export declare function stopNginx(dataDir: string): string
export declare function createServer(id: string, name: string, provider: Provider, version: string, ramMb: number, port: number, onlineMode: boolean, dataDir: string): Promise<string>
export declare function getServers(dataDir: string): Promise<Array<MinecraftServer>>
export declare function spawnContainer(id: string, binDir: string, ram: number): SpawnResult
export declare function streamLogs(id: string, callback: (err: Error | null, arg: string) => any): void
export declare function killContainers(): string
export declare function killContainer(id: string, force: boolean): Promise<string>
export interface SpawnResult {
  pid: number
  logPath: string
}
export declare class CreateServerRequest { }
